name: "Ops Terra EKS IaaC"
on:
    push:
        branches:
            - prod
            - dev
        paths:
            - terraform/**
    pull_request:
        branches:
            - prod
        paths:
            - terraform/**

env:
    AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_BUCKET_TF_STATE: ${{secrets.AWS_BUCKET_TF_STATE}}
    AWS_REGION: us-east-1
    EKS_CLUSTER: GitOps-eks

jobs:
    terraform:
        name: "Terraform code change applied"
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform

        steps:
            - name: Source code checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform init
              id: terra_init
              run: terraform init -backend-config="bucket=$AWS_BUCKET_TF_STATE"

            - name: Terraform format
              id: terra_fmt
              run: terraform fmt -check

            - name: Terraform validate
              id: terra_validate
              run: terraform validate

            - name: Terraform plan
              id: terra_plan
              run: terraform plan -no-color -input=false -out planfile
              continue-on-error: true

            - name: Terraform plan status
              if: steps.terra_plan.outcome == 'failure'
              run: exit 1
